theme: jekyll-theme-minimal
url: "https://crystal-dreams.org/"
baseurl: "/"

permalink: /:title/

title: "Solutions for your awakening life problems."
description: A new type of dream interpretation based on AI and expert dream interpreters to give you solutions for your awakening life problems."